version: '3.4'

services:
  fc.codeflix.catolog.fb:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: COD3fl1X.@

networks:
  default:
    name: service_catalog
    external: true